### ISSUE TITLE
did:peer resolver

### ISSUE THREAD

**Issue by hugoib** [ADORSYS-GIS/wallet-vc-libs#41]
This ticket and MR addresses the creation of did:peer methods in our codebase:

https://github.com/adorsys/eudiw-app/issues/272

Expand this to a did:peer resolver.

**Comment by hugoib** [comment]
Evaluate if it makes sense to just use DIDResolver from https://github.com/sicpa-dlab/didcomm-rust/blob/main/wasm/README.md

**Comment by nitch2019** [comment]
There is an overlapping with https://github.com/adorsys/eudiw-app/issues/226
We will decide how to move further with this ticket after coming forward with the other one

**Comment by hugoib** [comment]
On hold because of: https://github.com/adorsys/eudiw-app/issues/262

**Comment by hugoib** [comment]
Working on integrating the work from the mediator team.

**Comment by hugoib** [comment]
The work on this ticket is integrated into: https://github.com/adorsys/eudiw-app/issues/262

Closing this one.
