### ISSUE TITLE
Event driven didcomm architecture document

### ISSUE THREAD

**Issue by hugoib** [ADORSYS-GIS/wallet-vc-libs#42]
As on the wallet, we produced an architecture document outlining the service layer input/outputs and flows.

https://github.com/adorsys/eudiw-app/tree/main/docs/service-layer

This ticket is about creating an architecture document that will outline the implementation of didcomm with an event service layer.

**Comment by hugoib** [comment]
Basis for document: [Adorsys.pdf](https://github.com/user-attachments/files/17731068/Adorsys.pdf)

**Comment by hugoib** [comment]
Status: https://github.com/ADORSYS-GIS/wallet-vc-libs/tree/42-architecture-docs/docs/service-layer

**Comment by hugoib** [comment]
MR: https://github.com/ADORSYS-GIS/wallet-vc-libs/pull/49

**Comment by nitch2019** [comment]
@hugoib is back to you. Please check
