### ISSUE TITLE
Fix did:peer generator

### ISSUE THREAD

**Issue by hugoib** [ADORSYS-GIS/wallet-vc-libs#50]
The did peer generator is not generating properly the keys and keys IDs

**Comment by hugoib** [comment]
Could not find a did:peer 2 generator that works, beyond the example of https://github.com/roots-id/didcomm-mediator

There is no library we could use for this... Still troubleshooting what is wrong with the current implementation, error might be on keys generator? still on it.

**Comment by nitch2019** [comment]
@hugoib and @forkimenjeckayang will sync to discuss the problem

**Comment by hugoib** [comment]
This is how we did it on the mediator: https://github.com/adorsys/didcomm-mediator-rs/blob/main/crates/web-plugins/did-endpoint/src/didgen.rs#L6

**Comment by nitch2019** [comment]
About my ticket, I’m still trying to match what is expected by the library vs what we are generating. My approach of the new secrets format is still failing I have one last idea to try. Since the error is inside the wasm rust library, it’s tricky to debug and the raised error might be on another place (?)

**Comment by hugoib** [comment]
I moved forward from the secrets issue but now I have a new one: ![Image](https://github.com/user-attachments/assets/29e61ddb-8f55-4b98-bc07-bb4a15e0c7c2)

**Comment by hugoib** [comment]
For testing I am using an OOB inv from: https://mediator.rootsid.cloud

which resolves to:

![Image](https://github.com/user-attachments/assets/103a40c4-20de-4eb6-a491-e795202ee04e)

Apparently there is an error there where according to the spec serviceEndpoint should have a URI field ![Image](https://github.com/user-attachments/assets/7616fa1c-70d1-4390-b2a0-86b47ef34941)

**Comment by hugoib** [comment]
Needs proper adjustments and cleanups as seen here: feat/update-oob-contact-routing-explore

**Comment by forkimenjeckayang** [comment]
Pending PR to close this here:
- ADORSYS-GIS/wallet-vc-libs/#59

**Comment by nitch2019** [comment]
PR will be reviewed by @hugoib
