### ISSUE TITLE
Isolate and release the QR Scanner library to an artifact repository

### ISSUE THREAD

**Issue by hugoib** [ADORSYS-GIS/wallet-vc-libs#8]

**Comment by nitch2019** [comment]
Blocked by https://github.com/adorsys/eudiw-app/issues/252

**Comment by Awambeng** [comment]
pausing work on this ticket due to an issue with the current QR scanner library that was also encountered from its source. The team is currently exploring alternative solutions, and I'll resume work once we identify a viable approach.

**Comment by Awambeng** [comment]
The qr-scanner library is released and works perfectly!

**Comment by hugoib** [comment]
We should adapt the eudiw-app wallet to consume our library, then we don't have to do double work. In the future, if there is a bug with our implementation, we just fixed it in one place.
